#!/bin/bash

echo "🔧 ADD TEST DATA TO DATABASE"
echo "============================"
echo ""
echo "The database is empty, which is why the ingredient usage"
echo "isn't updating. We need to add test data to verify the"
echo "trigger is working correctly."
echo ""
echo "This SQL script will:"
echo "- Create a test user"
echo "- Add 3 test ingredients (Chicken Breast, Rice, Broccoli)"
echo "- Create a test meal"
echo "- Add meal ingredients to test the trigger"
echo "- Show the results to verify the trigger worked"
echo ""
echo "📋 SQL TO RUN IN SUPABASE DASHBOARD:"
echo "====================================="
echo ""
cat ADD_TEST_DATA_SQL.sql
echo ""
echo "📋 INSTRUCTIONS:"
echo "================"
echo "1. Go to https://supabase.com/dashboard"
echo "2. Click on your project: jdoitxsoquqaudygnbmh"
echo "3. Click 'SQL Editor' in the left sidebar"
echo "4. Click 'New Query'"
echo "5. Copy and paste the SQL above"
echo "6. Click 'Run' to execute the script"
echo ""
echo "🔍 AFTER RUNNING THE SQL:"
echo "========================="
echo "1. Check the results - you should see:"
echo "   - 3 ingredients with updated usage amounts"
echo "   - Usage percentages calculated correctly"
echo "2. Go back to your app: http://localhost:5173"
echo "3. Refresh the page - you should now see real data!"
echo "4. Try logging another meal to test the trigger"
echo ""
echo "✅ WHAT THIS WILL SHOW:"
echo "======================="
echo "- Chicken Breast: 2/4 pieces used (50.0%)"
echo "- Rice: 1.5/10 cups used (15.0%)"
echo "- Broccoli: 1/3 heads used (33.3%)"
echo "- The trigger should have updated amount_used automatically" 