#!/bin/bash

echo "🔧 FIX INGREDIENT USAGE TRIGGER"
echo "==============================="
echo ""
echo "The dashboard is not updating ingredient usage data because"
echo "the database trigger that automatically updates amount_used"
echo "when meal ingredients are added is missing."
echo ""
echo "This trigger should:"
echo "- Update amount_used when meal_ingredients are added"
echo "- Update amount_used when meal_ingredients are updated"
echo "- Update amount_used when meal_ingredients are deleted"
echo "- Calculate meal total_cost automatically"
echo ""
echo "📋 SQL TO RUN IN SUPABASE DASHBOARD:"
echo "====================================="
echo ""
cat CREATE_INGREDIENT_TRIGGER.sql
echo ""
echo "📋 INSTRUCTIONS:"
echo "================"
echo "1. Go to https://supabase.com/dashboard"
echo "2. Click on your project: jdoitxsoquqaudygnbmh"
echo "3. Click 'SQL Editor' in the left sidebar"
echo "4. Click 'New Query'"
echo "5. Copy and paste the SQL above"
echo "6. Click 'Run' to execute the script"
echo ""
echo "🔍 AFTER RUNNING THE SQL:"
echo "========================="
echo "1. Go back to your app: http://localhost:5173"
echo "2. Try logging a meal with ingredients"
echo "3. Check the dashboard - usage data should now update!"
echo ""
echo "✅ WHAT THIS FIXES:"
echo "==================="
echo "- Dashboard will show correct amount_used values"
echo "- Progress bars will reflect actual usage"
echo "- Percentage used will be accurate"
echo "- Amount remaining will be calculated correctly"
echo "- Meal costs will be calculated automatically" 