#!/bin/bash

echo "🔧 FIX MEALS COLUMN NAME MISMATCH"
echo "=================================="
echo ""
echo "The meals table has a column name mismatch:"
echo "- Database has: 'name' column"
echo "- App expects: 'meal_name' column"
echo ""
echo "This is causing the 'createMeal is not a function' error"
echo "because the database schema doesn't match what the app expects."
echo ""
echo "📋 SQL TO RUN IN SUPABASE DASHBOARD:"
echo "====================================="
echo ""
cat FIX_MEALS_COLUMN.sql
echo ""
echo "📋 INSTRUCTIONS:"
echo "================"
echo "1. Go to https://supabase.com/dashboard"
echo "2. Click on your project: jdoitxsoquqaudygnbmh"
echo "3. Click 'SQL Editor' in the left sidebar"
echo "4. Click 'New Query'"
echo "5. Copy and paste the SQL above"
echo "6. Click 'Run'"
echo "7. You should see verification results showing the renamed column"
echo ""
echo "🎯 After running this, try logging a meal again"
echo "   The 'createMeal is not a function' error should be resolved!"
echo ""
echo "📊 The script will:"
echo "   - Rename 'name' column to 'meal_name'"
echo "   - Verify the column was renamed correctly"
echo "   - Test the table structure" 