#!/bin/bash

echo "🔧 QUICK FIX: DATE COLUMN ISSUE"
echo "================================"
echo ""
echo "The app expects 'date_cooked' but the database has 'meal_date'"
echo ""
echo "📋 SQL TO RUN IN SUPABASE DASHBOARD:"
echo "====================================="
echo ""
cat FIX_DATE_COLUMN.sql
echo ""
echo "📋 INSTRUCTIONS:"
echo "================"
echo "1. Go to https://supabase.com/dashboard"
echo "2. Click on your project: jdoitxsoquqaudygnbmh"
echo "3. Click 'SQL Editor' in the left sidebar"
echo "4. Click 'New Query'"
echo "5. Copy and paste the SQL above"
echo "6. Click 'Run'"
echo "7. You should see 'No rows returned' (success!)"
echo ""
echo "🎯 After running this, refresh your app at http://localhost:5173"
echo "   The 'Database Setup Required' error should be completely gone!" 