#!/bin/bash

echo "🚀 QUICK FIX - Copy this SQL and run it in Supabase:"
echo "====================================================="
echo ""
echo "-- Add price column to fix 'Database Setup Required' error"
echo "ALTER TABLE ingredients ADD COLUMN price DECIMAL(10,2) NOT NULL DEFAULT 0.00;"
echo "COMMENT ON COLUMN ingredients.price IS 'Total cost of purchasing this ingredient';"
echo ""
echo "📋 Steps:"
echo "1. Go to https://supabase.com/dashboard"
echo "2. Click 'SQL Editor' → 'New query'"
echo "3. Copy the ALTER TABLE command above"
echo "4. Click 'Run'"
echo "5. Refresh your app at http://localhost:5173"
echo ""
echo "🎉 That's it! The error should disappear." 