#!/bin/bash

echo "🔧 QUICK FIX: MISSING INGREDIENT COLUMNS"
echo "========================================"
echo ""
echo "The ingredients table is missing required columns:"
echo "- amount_purchased (quantity purchased)"
echo "- purchase_date (when purchased)"
echo "- amount_used (quantity used in meals)"
echo "- amount_remaining (calculated remaining quantity)"
echo ""
echo "📋 SQL TO RUN IN SUPABASE DASHBOARD:"
echo "====================================="
echo ""
cat ADD_MISSING_COLUMNS.sql
echo ""
echo "📋 INSTRUCTIONS:"
echo "================"
echo "1. Go to https://supabase.com/dashboard"
echo "2. Click on your project: jdoitxsoquqaudygnbmh"
echo "3. Click 'SQL Editor' in the left sidebar"
echo "4. Click 'New Query'"
echo "5. Copy and paste the SQL above"
echo "6. Click 'Run'"
echo "7. You should see verification results showing the new columns"
echo ""
echo "🎯 After running this, try adding an ingredient again"
echo "   The error should be resolved and ingredients should save successfully!"
echo ""
echo "📊 The script will:"
echo "   - Add all missing columns with proper data types"
echo "   - Set default values for existing data"
echo "   - Create a calculated field for remaining quantity"
echo "   - Verify the changes were applied correctly" 